<a href="https://colab.research.google.com/github/ZIXIANG2025/Tutorial_03/blob/Tutorial/tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array=np.array([[1,2],[3,4]])
print(array)

[[1 2]
 [3 4]]


In [ ]:
import numpy as np
array=np.random.random((3,4))
print(array)


[[0.52304698 0.52226939 0.73307954 0.0967458 ]
 [0.25776947 0.7551946  0.28831319 0.06601093]
 [0.80155968 0.30620523 0.13632385 0.04578331]]


In [ ]:
import numpy as np
array1=np.ones((2,2))
array2=np.zeros((2,2))
print(array1)
print(array2)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
array=np.random.random((6,3))
print(array)
print(np.transpose(array))
#print(array.T)

[[0.67577624 0.59268814 0.26319121]
 [0.69396264 0.57368871 0.00944738]
 [0.7978737  0.22409348 0.00668566]
 [0.85423126 0.09636934 0.82720088]
 [0.62915697 0.60168317 0.09290402]
 [0.44446428 0.97880622 0.1193605 ]]
[[0.67577624 0.69396264 0.7978737  0.85423126 0.62915697 0.44446428]
 [0.59268814 0.57368871 0.22409348 0.09636934 0.60168317 0.97880622]
 [0.26319121 0.00944738 0.00668566 0.82720088 0.09290402 0.1193605 ]]


In [5]:
import numpy as np
array1=np.array([[1,2],[3,4]])
array2=np.array([[5,6,7],[8,9,10],])
dot=np.dot(array1,array2)
#dot=array1@array2
print(dot)


[[21 24 27]
 [47 54 61]]
